#!/usr/bin/env python3
"""セッションログ(.jsonl)から、人間の発言とAIの応答をターン単位で抽出する。

使い方:
    python3 extract.py <session-id | jsonl path> [出力先.json]

出力(JSON): {"meta": {...}, "turns": [{"n","ts","user","ai","tools","agents"}, ...]}
  - user : 実際に人間が打った内容（スキル本文の展開・システム注入は除去済み）
  - ai   : そのターンでAIが返したテキストを " / " で連結したもの
  - tools: ツール実行回数
  - agents: サブエージェント委譲回数
"""
import json
import os
import re
import sys
import glob

PROJECTS = os.path.expanduser("~/.claude/projects")

# 人間の入力ではない、システム側が注入するもの
NOISE_PREFIXES = (
    "Base directory for this skill",
    "<local-command-caveat>",
    "<local-command-stdout>",
    "Caveat: The messages below were generated by the user",
)
NOISE_PATTERNS = (
    re.compile(r"^\s*<task-notification>", re.S),
    re.compile(r"^\s*<system-reminder>", re.S),
    re.compile(r"^\s*This session is being continued from a previous conversation", re.S),
)


def find_log(arg):
    """セッションIDまたはパスから .jsonl を見つける。"""
    if os.path.isfile(arg):
        return arg

    if not os.path.isdir(PROJECTS):
        sys.exit(
            f"セッションログの置き場が見つかりません: {PROJECTS}\n"
            "このスキルは Claude Code のログ形式（1行1JSONの .jsonl）を前提にしています。\n"
            "他のエージェントで使う場合は、同じ形式のログのパスを直接渡してください。"
        )

    hits = glob.glob(os.path.join(PROJECTS, "*", f"{arg}*.jsonl"))
    if not hits:
        sys.exit(
            f"セッションログが見つかりません: {arg}\n"
            f"探した場所: {PROJECTS}/*/\n"
            "セッションIDは部分一致でも指定できます。一覧は次で確認できます:\n"
            f"  ls -t {PROJECTS}/*/*.jsonl | head"
        )
    # 同名が複数あるときは最大のものを使う（本体である可能性が高い）
    return max(hits, key=os.path.getsize)


def clean_user_text(t):
    """人間の入力から、システム由来のノイズを取り除く。

    戻り値: (表示用テキスト, 種別)  種別は "human" / "notification" / None(捨てる)
    """
    s = t.strip()
    if not s:
        return None, None
    if s.startswith(NOISE_PREFIXES):
        return None, None
    for p in NOISE_PATTERNS:
        if p.match(s):
            # 完了通知だけは「AIが自発的に動いた区切り」として残す価値がある
            if s.lstrip().startswith("<task-notification>"):
                m = re.search(r"<summary>(.*?)</summary>", s, re.S)
                label = m.group(1).strip() if m else "バックグラウンド処理"
                return f"（{label} の完了通知）", "notification"
            return None, None

    # スラッシュコマンドは <command-name> + <command-args> に展開されている
    cm = re.search(r"<command-name>(.*?)</command-name>", s, re.S)
    if cm:
        ca = re.search(r"<command-args>(.*?)</command-args>", s, re.S)
        s = cm.group(1).strip() + (" " + ca.group(1).strip() if ca else "")

    # IDE の選択範囲は本文ではないので畳む
    s = re.sub(
        r"<ide_selection>The user selected the lines .*?from ([^:]*):(.*?)</ide_selection>",
        r"（エディタで選択: \2）",
        s,
        flags=re.S,
    )
    s = re.sub(r"<[^>]+>", " ", s)
    s = " ".join(s.split())
    return (s, "human") if s else (None, None)


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    path = find_log(sys.argv[1])
    out = sys.argv[2] if len(sys.argv) > 2 else None

    turns = []
    cur = None
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        if d.get("type") not in ("user", "assistant"):
            continue
        # サブエージェント内部の往復は本筋ではないので除く
        if d.get("isSidechain"):
            continue

        msg = d.get("message") or {}
        content = msg.get("content")
        blocks = [{"type": "text", "text": content}] if isinstance(content, str) else content
        if not isinstance(blocks, list):
            continue

        for b in blocks:
            if not isinstance(b, dict):
                continue
            bt = b.get("type")

            if d["type"] == "user":
                if bt != "text":
                    continue
                text, kind = clean_user_text(b.get("text", ""))
                if not text:
                    continue
                cur = {
                    "n": len(turns) + 1,
                    "ts": d.get("timestamp", ""),
                    "user": text,
                    "kind": kind,
                    "ai": [],
                    "tools": 0,
                    "agents": 0,
                }
                turns.append(cur)
            else:
                if cur is None:
                    continue
                if bt == "text":
                    t = " ".join(b.get("text", "").split())
                    if t:
                        cur["ai"].append(t)
                elif bt == "tool_use":
                    cur["tools"] += 1
                    if b.get("name") == "Agent":
                        cur["agents"] += 1

    for t in turns:
        t["ai"] = " / ".join(t["ai"])

    tools = sum(t["tools"] for t in turns)
    result = {
        "meta": {
            "log": path,
            "session_id": os.path.basename(path).replace(".jsonl", ""),
            "turns": len(turns),
            "tools": tools,
            "agents": sum(t["agents"] for t in turns),
            "start": turns[0]["ts"] if turns else "",
            "end": turns[-1]["ts"] if turns else "",
        },
        "turns": turns,
    }

    text = json.dumps(result, ensure_ascii=False, indent=1)
    if out:
        open(out, "w", encoding="utf-8").write(text)
        m = result["meta"]
        print(f"{out} に書き出しました")
        print(f"  ターン {m['turns']} / ツール {m['tools']} / 委譲 {m['agents']}")
        print(f"  {m['start'][:16]} → {m['end'][:16]}")
    else:
        print(text)


if __name__ == "__main__":
    main()
