#!/usr/bin/env python3
"""Claude Code のセッションログから、人間の発言とAIの応答をターン単位で抽出する。

使い方:
    python3 extract.py <セッションID | ログのパス> [出力先.json]
    python3 extract.py --list        # 見つかるログを新しい順に一覧

出力(JSON): {"meta": {...}, "turns": [{"n","ts","user","kind","ai","tools","agents"}]}

これは Claude Code 形式の便宜ツール。他のエージェントで使うときは、
自分のログの場所と構造は自分が知っているはずなので、これを使うより
その場で読み出すほうが速い（SKILL.md の手順1を参照）。

このスクリプトの本体は「何を捨てるか」の知識にある。生ログには
人間が打っていないものが大量に混ざっていて、そのまま数えると実態とずれる。
その判断は clean_user_text() に集約してある。
"""
import glob
import json
import os
import re
import sys

PROJECTS = os.path.expanduser("~/.claude/projects")

# 人間の入力に見えるが、実際はシステムが注入しているもの。
# 実ログを読んで見つけたものだけを列挙している。
NOISE_PREFIXES = (
    "Base directory for this skill",   # スキル本文の展開
    "<local-command-caveat>",
    "<local-command-stdout>",
    "Caveat: The messages below were generated by the user",
)
NOISE_PATTERNS = (
    re.compile(r"^\s*<task-notification>", re.S),
    re.compile(r"^\s*<system-reminder>", re.S),
    re.compile(r"^\s*This session is being continued from a previous conversation", re.S),
)


def die(msg):
    sys.exit(msg)


def find_log(arg):
    """セッションIDまたはパスから .jsonl を1つ決める。"""
    if os.path.isfile(arg):
        return arg
    if not os.path.isdir(PROJECTS):
        die(
            f"Claude Code のログが見つかりません: {PROJECTS}\n"
            "他のエージェントで使う場合は、ログのパスを直接渡すか、\n"
            "SKILL.md の手順1にしたがって自分でログを読んでください。"
        )
    hits = [p for p in glob.glob(os.path.join(PROJECTS, "*", "*.jsonl"))
            if arg in os.path.basename(p)]
    if not hits:
        die(f"'{arg}' に一致するログがありません。--list で一覧できます。")
    # 同じIDが複数あるときは中身が多いものを本体とみなす
    return max(hits, key=os.path.getsize)


def clean_user_text(t):
    """人間の入力から、システム由来のノイズを取り除く。

    ここがこのスクリプトの核。戻り値は (表示用テキスト, 種別)。
    種別は "human" / "notification"、捨てるなら (None, None)。
    """
    s = (t or "").strip()
    if not s:
        return None, None
    if s.startswith(NOISE_PREFIXES):
        return None, None
    for p in NOISE_PATTERNS:
        if p.match(s):
            # 完了通知だけは「AIが自発的に動いた区切り」として残す価値がある
            if s.lstrip().startswith("<task-notification>"):
                m = re.search(r"<summary>(.*?)</summary>", s, re.S)
                label = m.group(1).strip() if m else "バックグラウンド処理"
                return f"（{label} の完了通知）", "notification"
            return None, None

    # スラッシュコマンドは <command-name> + <command-args> に展開されている
    cm = re.search(r"<command-name>(.*?)</command-name>", s, re.S)
    if cm:
        ca = re.search(r"<command-args>(.*?)</command-args>", s, re.S)
        s = cm.group(1).strip() + (" " + ca.group(1).strip() if ca else "")

    # IDE の選択範囲は本文ではないので畳む
    s = re.sub(
        r"<ide_selection>The user selected the lines .*?from ([^:]*):(.*?)</ide_selection>",
        r"（エディタで選択: \2）",
        s,
        flags=re.S,
    )
    s = re.sub(r"<[^>]+>", " ", s)
    s = " ".join(s.split())
    return (s, "human") if s else (None, None)


def cmd_list():
    files = glob.glob(os.path.join(PROJECTS, "*", "*.jsonl"))
    if not files:
        die(f"ログが見つかりません: {PROJECTS}")
    import datetime
    for path in sorted(files, key=os.path.getmtime, reverse=True)[:25]:
        when = datetime.datetime.fromtimestamp(os.path.getmtime(path)).strftime("%m-%d %H:%M")
        size = os.path.getsize(path)
        unit = f"{size/1024/1024:.1f}M" if size > 1024 * 1024 else f"{size//1024}K"
        print(f"{when}  {unit:>6s}  {path}")


def main():
    args = sys.argv[1:]
    if not args:
        sys.exit(__doc__)
    if "--list" in args:
        cmd_list()
        return

    path = find_log(args[0])
    out = args[1] if len(args) > 1 else None

    turns, cur = [], None
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.strip()
        if not line:
            continue
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        if d.get("type") not in ("user", "assistant"):
            continue
        # サブエージェント内部の往復は本筋ではない
        if d.get("isSidechain"):
            continue

        content = (d.get("message") or {}).get("content")
        blocks = [{"type": "text", "text": content}] if isinstance(content, str) else content
        if not isinstance(blocks, list):
            continue

        for b in blocks:
            if not isinstance(b, dict):
                continue
            bt = b.get("type")
            if d["type"] == "user":
                if bt != "text":
                    continue
                text, kind = clean_user_text(b.get("text", ""))
                if not text:
                    continue
                cur = {
                    "n": len(turns) + 1,
                    "ts": d.get("timestamp", ""),
                    "user": text,
                    "kind": kind,
                    "ai": [],
                    "tools": 0,
                    "agents": 0,
                }
                turns.append(cur)
            else:
                if cur is None:
                    continue
                if bt == "text":
                    t = " ".join(b.get("text", "").split())
                    if t:
                        cur["ai"].append(t)
                elif bt == "tool_use":
                    cur["tools"] += 1
                    if b.get("name") == "Agent":
                        cur["agents"] += 1

    if not turns:
        die(f"会話が取れませんでした: {path}\n  head -c 800 {path} で中身を確認してください。")

    for t in turns:
        t["ai"] = " / ".join(t["ai"])

    result = {
        "meta": {
            "log": path,
            "session_id": os.path.basename(path).replace(".jsonl", ""),
            "turns": len(turns),
            "tools": sum(t["tools"] for t in turns),
            "agents": sum(t["agents"] for t in turns),
            "start": turns[0]["ts"],
            "end": turns[-1]["ts"],
        },
        "turns": turns,
    }

    text = json.dumps(result, ensure_ascii=False, indent=1)
    if out:
        open(out, "w", encoding="utf-8").write(text)
        m = result["meta"]
        print(f"{out} に書き出しました")
        print(f"  ターン {m['turns']} / ツール {m['tools']} / 委譲 {m['agents']}")
        print(f"  {m['start'][:16]} → {m['end'][:16]}")
    else:
        print(text)


if __name__ == "__main__":
    main()
